---
- name: Install PostgreSQL on Debian-based systems
  hosts: debian_servers
  become: yes
  vars_files:
    - vars/postgresql_vars.yml  # Optional, if you have additional variables

  tasks:
    - name: Install prerequisites (curl and ca-certificates)
      apt:
        name:
          - curl
          - ca-certificates
        state: present

    - name: Install postgresql-common package
      apt:
        name: postgresql-common
        state: present

    - name: Ensure the pgdg directory exists
      file:
        path: /usr/share/postgresql-common/pgdg
        state: directory

    - name: Add PostgreSQL APT repository key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL APT repository
      lineinfile:
        path: /etc/apt/sources.list.d/pgdg.list
        line: "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        create: yes

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted
