- name: Remove PostgreSQL from Debian-based systems
  hosts: debian_servers
  become: yes

  tasks:
    - name: Stop PostgreSQL service if it exists
      service:
        name: postgresql
        state: stopped
      ignore_errors: yes  # Continue even if the service is not found

    - name: Remove PostgreSQL and related packages
      apt:
        name: 
          - postgresql
          - postgresql-common
          - postgresql-client
          - postgresql-contrib
          - libpq-dev
        state: absent
        purge: yes

    - name: Remove PostgreSQL data directory
      file:
        path: /var/lib/postgresql
        state: absent
       

    - name: Remove PostgreSQL configuration files
      file:
        path: /etc/postgresql
        state: absent
        

    - name: Remove PostgreSQL log files
      file:
        path: /var/log/postgresql
        state: absent
        

    - name: Remove PostgreSQL APT source list
      file:
        path: /etc/apt/sources.list.d/pgdg.list
        state: absent

    - name: Remove downloaded PostgreSQL repository key
      file:
        path: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
        state: absent

    - name: Remove PostgreSQL APT repository key
      apt_key:
        id: ACCC4CF8
        state: absent
      ignore_errors: yes  # Handle cases where gpg is missing

    - name: Remove the pgdg directory
      file:
        path: /usr/share/postgresql-common/pgdg
        state: absent

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Check if PostgreSQL command is still accessible
      shell: psql --version
      register: psql_check
      ignore_errors: yes

    - name: Fail if PostgreSQL is still accessible
      fail:
        msg: "PostgreSQL is still accessible!"
      when: psql_check.rc == 0
