- name: Ensure PostgreSQL is completely removed from Debian-based systems
  hosts: debian_servers
  become: yes

  tasks:
    - name: Stop PostgreSQL service
      service:
        name: postgresql
        state: stopped
      ignore_errors: yes

    - name: Remove PostgreSQL and related packages
      apt:
        name: 
          - postgresql
          - postgresql-common
          - postgresql-client
          - postgresql-contrib
          - libpq-dev
        state: absent
        purge: yes

    - name: Remove PostgreSQL data directory
      file:
        path: /var/lib/postgresql
        state: absent

    - name: Remove PostgreSQL configuration files
      file:
        path: /etc/postgresql
        state: absent

    - name: Remove PostgreSQL log files
      file:
        path: /var/log/postgresql
        state: absent

    - name: Remove PostgreSQL APT source list
      file:
        path: /etc/apt/sources.list.d/pgdg.list
        state: absent

    - name: Remove APT repository key for PostgreSQL
      apt_key:
        id: ACCC4CF8
        state: absent

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Check if PostgreSQL command is still accessible
      shell: psql --version
      register: psql_check
      ignore_errors: yes

    - name: Fail if PostgreSQL is still accessible
      fail:
        msg: "PostgreSQL is still accessible!"
      when: psql_check.rc == 0

