- name: Remove PostgreSQL from Debian-based systems
  hosts: debian_servers
  become: yes

  tasks:
    - name: Stop PostgreSQL service if it exists
      service:
        name: postgresql
        state: stopped
      ignore_errors: yes  # Continue even if the service is not found

    - name: Remove PostgreSQL and related packages
      apt:
        name: 
          - postgresql
          - postgresql-common
          - postgresql-client
          - postgresql-contrib
          - libpq-dev
        state: absent
        purge: yes

    - name: Remove PostgreSQL data directory
      file:
        path: /var/lib/postgresql
        state: absent
        

    - name: Remove PostgreSQL configuration files
      file:
        path: /etc/postgresql
        state: absent
        

    - name: Remove PostgreSQL log files
      file:
        path: /var/log/postgresql
        state: absent
        

    - name: Remove PostgreSQL APT source list
      file:
        path: /etc/apt/sources.list.d/pgdg.list
        state: absent

    - name: Remove downloaded PostgreSQL repository key
      file:
        path: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
        state: absent

    - name: Remove PostgreSQL APT repository key
      apt_key:
        id: ACCC4CF8
        state: absent
      ignore_errors: yes  # Handle cases where gpg is missing

    - name: Remove the pgdg directory
      file:
        path: /usr/share/postgresql-common/pgdg
        state: absent
       

    - name: Remove PostgreSQL binaries if found
      file:
        path: /usr/local/bin/psql  # Adjust this path based on your search results
        state: absent
      ignore_errors: yes

    - name: Remove any additional PostgreSQL installation paths
      file:
        path: /opt/postgresql  # Example path; adjust as necessary
        state: absent
        recurse: yes
      ignore_errors: yes

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Restart the server to ensure all services are stopped
      reboot:
        msg: "Rebooting the server to finalize PostgreSQL removal"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30

    - name: Verify PostgreSQL is no longer accessible
      shell: "which psql"
      register: psql_check
      changed_when: false
      ignore_errors: yes

    - name: Confirm PostgreSQL is not found
      fail:
        msg: "PostgreSQL is still accessible!"
      when: psql_check.stdout != ""
